version: "3.7"

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5432:5432"
    networks:
      - podcast_net

  airflow:
    build: ./airflow
    image: custom-airflow:latest
    restart: always
    depends_on:
      - postgres
    environment:
      # Use LocalExecutor and point to Postgres
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__API__AUTH_BACKENDS: "airflow.api.auth.backend.basic_auth"
    ports:
      - "8080:8080"
    volumes:
      - ./data:/data
      - ./airflow/dags:/opt/airflow/dags
      - /var/run/docker.sock:/var/run/docker.sock
    command: ["standalone"]
    networks:
      - podcast_net

  spark-master:
    image: bitnami/spark:3.3.0
    environment:
      - SPARK_MODE=master
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "7077:7077"
      - "8081:8081"
    networks:
      - podcast_net

  spark-worker:
    image: bitnami/spark:3.3.0
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - ALLOW_EMPTY_PASSWORD=yes
    depends_on:
      - spark-master
    networks:
      - podcast_net

  spark-app:
    build: ./spark-app
    image: spark-app:latest
    depends_on:
      - spark-master
      - spark-worker
    environment:
      SPARK_MASTER: spark://spark-master:7077
    volumes:
      - ./data:/data
    networks:
      - podcast_net

networks:
  podcast_net:
    name: podcast_net    # ← force Docker to actually call it "podcast_net"
    driver: bridge